/* Action types */
// Items
export const RECEIVE_ITEMS = 'RECEIVE_ITEMS';
export const RECEIVE_ITEMS_LOADING = 'RECEIVE_ITEMS_LOADING';
export const RECEIVE_ITEMS_FAILURE = 'RECEIVE_ITEMS_FAILURE';

// Item
export const SELECT_ITEM = 'SELECT_ITEM';
export const DESELECT_ITEM = 'DESELECT_ITEM';
export const RECEIVE_ITEM = 'RECEIVE_ITEM';
export const RECEIVE_ITEM_LOADING = 'RECEIVE_ITEM_LOADING';
export const RECEIVE_ITEM_FAILURE = 'RECEIVE_ITEM_FAILURE';

// Favorites
export const FAVORITE_ITEM = 'FAVORITE_ITEM';
export const DEFAVORITE_ITEM = 'DEFAVORITE_ITEM';
export const RECEIVE_FAVORITES = 'RECEIVE_FAVORITES';